"""Full simulation tick via one NVIDIA NIM call (DGX Spark)."""

from __future__ import annotations

import json
import logging

from backend.agents.nim_client import nim_client, parse_json_object
from backend.config import NIM_MODEL
from backend.schemas.simulation import SimulationRunResponse
from backend.simulation.tick_response_builder import build_simulation_response

logger = logging.getLogger(__name__)

SYSTEM_PROMPT = """detailed thinking off
You are the GridFlex multi-agent controller for Toronto's 25-ward flex grid.
Roles you perform in ONE response: Grid Forecast Agent, 25 Ward Agents, Reporter Agent.

Return JSON only (no markdown) with this structure:
{
  "grid_prediction": {
    "event_type": "normal|demand_spike|outage_risk|surplus",
    "risk_level": "normal|medium|high|critical",
    "grid_stress_probability": 0.0-1.0,
    "target_reduction_mw": integer,
    "predicted_duration_minutes": integer,
    "drivers": ["...", "..."]
  },
  "ward_predictions": [
    {
      "ward_id": "ward_01",
      "ward_name": "Ward name",
      "event_type": "normal|demand_spike|...",
      "risk_level": "normal|medium|high|critical",
      "event_probability": 0.0-1.0,
      "predicted_duration_minutes": integer,
      "recommended_action": "none|reduce_load|shift_load|increase_load_or_charge_storage",
      "recommended_bid_mw": number,
      "submit_bid": boolean,
      "bid_quantity_mw": number,
      "bid_price_per_mwh": number,
      "confidence": 0.0-1.0,
      "drivers": ["..."]
    }
  ],
  "reporter": {
    "title": "...",
    "severity": "normal|medium|high|critical",
    "summary": "...",
    "market_action": "...",
    "impact": "...",
    "operator_note": "Generated by NVIDIA NIM on DGX Spark."
  }
}

Rules:
- Exactly 25 entries in ward_predictions (ward_01 .. ward_25).
- submit_bid=true only when recommended_action is not none and bid_quantity_mw > 0.
- Respect ward flexible capacity limits from input.
- During spikes, coordinate realistic flex bids across wards.
"""


class LLMOrchestratorAgent:
    agent_id = "agent_llm_orchestrator"
    model_version = f"nim-{NIM_MODEL}"

    async def run_tick(
        self,
        *,
        timestamp: str,
        system_features: dict,
        ward_features: list[dict],
        ward_names: dict[str, str],
        snapshot: dict | None,
        stress_before: int,
    ) -> SimulationRunResponse:
        payload = {
            "timestamp": timestamp,
            "system_features": system_features,
            "ward_features": ward_features,
            "stress_score_before": stress_before,
        }
        raw = await nim_client.chat_completion(
            [
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": json.dumps(payload)},
            ],
            max_tokens=4096,
            temperature=0.15,
        )
        parsed = parse_json_object(raw)
        features_by_ward = {w["ward_id"]: w for w in ward_features}
        return build_simulation_response(
            parsed,
            timestamp=timestamp,
            ward_names=ward_names,
            features_by_ward=features_by_ward,
            snapshot=snapshot or {},
            stress_before=stress_before,
            agent_mode="llm",
            model_label=NIM_MODEL,
            grid_driver_default="NIM orchestrator",
            ward_driver_default="NIM ward agent",
            bid_reason="nim_ward_agent",
            reporter_title_default="GridFlex NIM alert",
            operator_note_default="Generated by NVIDIA NIM on DGX Spark.",
        )


llm_orchestrator = LLMOrchestratorAgent()
