"""Full simulation tick via NemoClaw / OpenClaw agent turn."""

from __future__ import annotations

import logging

from backend.agents.nemoclaw_client import nemoclaw_client
from backend.config import NEMOCLAW_AGENT_ID
from backend.schemas.simulation import SimulationRunResponse
from backend.simulation.tick_response_builder import build_simulation_response

logger = logging.getLogger(__name__)


class NemoClawOrchestratorAgent:
    agent_id = "agent_nemoclaw_orchestrator"
    model_version = f"nemoclaw-{NEMOCLAW_AGENT_ID}"

    async def run_tick(
        self,
        *,
        timestamp: str,
        system_features: dict,
        ward_features: list[dict],
        ward_names: dict[str, str],
        snapshot: dict | None,
        stress_before: int,
    ) -> SimulationRunResponse:
        payload = {
            "timestamp": timestamp,
            "system_features": system_features,
            "ward_features": ward_features,
            "stress_score_before": stress_before,
        }
        parsed = await nemoclaw_client.run_tick_turn(payload)
        features_by_ward = {w["ward_id"]: w for w in ward_features}
        return build_simulation_response(
            parsed,
            timestamp=timestamp,
            ward_names=ward_names,
            features_by_ward=features_by_ward,
            snapshot=snapshot or {},
            stress_before=stress_before,
            agent_mode="nemoclaw",
            model_label=self.model_version,
            grid_driver_default="NemoClaw orchestrator",
            ward_driver_default="NemoClaw ward agent",
            bid_reason="nemoclaw_ward_agent",
            reporter_title_default="GridFlex NemoClaw alert",
            operator_note_default="Generated by NVIDIA NemoClaw on OpenClaw.",
        )


nemoclaw_orchestrator = NemoClawOrchestratorAgent()
