"""Reporter / Alert Agent — template fallback + optional NVIDIA NIM (local device)."""

from __future__ import annotations

import json
import logging

from backend.agents.nim_client import nim_client, parse_json_object
from backend.config import REPORTER_MODE
from backend.schemas.simulation import (
    MarketClearResponse,
    OperatorAlert,
    ReporterOutput,
    SystemPredictionDetail,
)

logger = logging.getLogger(__name__)


class ReporterAgent:
    agent_id = "agent_reporter"

    def build_alert(
        self,
        system: SystemPredictionDetail,
        market: MarketClearResponse,
    ) -> ReporterOutput:
        return self._template_alert(system, market)

    async def build_alert_async(
        self,
        system: SystemPredictionDetail,
        market: MarketClearResponse,
    ) -> ReporterOutput:
        if REPORTER_MODE != "llm":
            return self._template_alert(system, market)

        try:
            return await self._llm_alert(system, market)
        except Exception:
            logger.exception("NIM reporter failed; using template fallback")
            fallback = self._template_alert(system, market)
            fallback.alert.operator_note = (
                "GridFlex LLM reporter unreachable — template fallback active."
            )
            return fallback

    def _template_alert(
        self,
        system: SystemPredictionDetail,
        market: MarketClearResponse,
    ) -> ReporterOutput:
        clearing = market.clearing_result
        severity = system.risk_level.value
        title = f"Grid stress {system.risk_level.value.upper()} — {system.event_type.value.replace('_', ' ')}"

        summary = (
            f"System stress score {clearing.stress_score_before} → "
            f"{clearing.stress_score_after}. "
            f"Target reduction {clearing.target_reduction_mw} MW; "
            f"accepted {clearing.accepted_reduction_mw} MW "
            f"({clearing.clearing_status})."
        )

        if clearing.unfilled_reduction_mw > 0:
            market_action = (
                f"Partial clear — {clearing.unfilled_reduction_mw:.0f} MW unfilled. "
                "Consider manual dispatch or price adjustment."
            )
        elif clearing.target_reduction_mw > 0:
            market_action = (
                f"Cleared at ${clearing.clearing_price_per_mwh:.0f}/MWh "
                f"across {len(market.accepted_bids)} ward bids."
            )
        else:
            market_action = "No flex dispatch required — grid within normal bounds."

        impact = (
            f"Duration ~{system.predicted_duration_minutes} min. "
            f"Drivers: {', '.join(system.drivers[:3])}."
        )

        return ReporterOutput(
            alert=OperatorAlert(
                title=title,
                severity=severity,
                summary=summary,
                market_action=market_action,
                impact=impact,
                operator_note="GridFlex simulated flex-market dispatch (historical replay mode).",
            )
        )

    async def _llm_alert(
        self,
        system: SystemPredictionDetail,
        market: MarketClearResponse,
    ) -> ReporterOutput:
        payload = {
            "system_prediction": system.model_dump(mode="json"),
            "clearing_result": market.clearing_result.model_dump(mode="json"),
            "accepted_bid_count": len(market.accepted_bids),
            "accepted_bids_sample": [
                b.model_dump(mode="json") for b in market.accepted_bids[:8]
            ],
        }

        messages = [
            {
                "role": "system",
                "content": (
                    "detailed thinking off\n"
                    "You are a Toronto grid operator assistant for GridFlex AI. "
                    "Respond with JSON only, no markdown, keys: "
                    "title, severity, summary, market_action, impact, operator_note. "
                    "severity must be one of: normal, medium, high, critical. "
                    "Keep summary under 2 sentences; be actionable."
                ),
            },
            {
                "role": "user",
                "content": json.dumps(payload),
            },
        ]

        raw = await nim_client.chat_completion(messages, max_tokens=512)
        parsed = parse_json_object(raw)

        return ReporterOutput(
            alert=OperatorAlert(
                title=str(parsed.get("title", "GridFlex operator alert")),
                severity=str(parsed.get("severity", system.risk_level.value)),
                summary=str(parsed.get("summary", "")),
                market_action=str(parsed.get("market_action", "")),
                impact=str(parsed.get("impact", "")),
                operator_note=str(
                    parsed.get(
                        "operator_note",
                        "Generated by NVIDIA NIM on local device.",
                    )
                ),
            )
        )


reporter_agent = ReporterAgent()
