"""Build SimulationRunResponse from orchestrator JSON (NIM or NemoClaw)."""

from __future__ import annotations

import uuid
from datetime import datetime, timedelta, timezone

from backend.agents.market_clearing_agent import market_clearing_agent
from backend.schemas.simulation import (
    Bid,
    BidType,
    DispatchStatus,
    EventType,
    MarketContext,
    OperatorAlert,
    RecommendedAction,
    ReporterOutput,
    RiskLevel,
    SimulationRunResponse,
    SystemPredictionDetail,
    WardAgentDecision,
    WardPrediction,
)
from backend.simulation.kepler_export import build_kepler_flows, build_kepler_nodes


def system_features_hour(snapshot: dict, ward_raw: dict) -> int:
    sim = snapshot.get("sim") if isinstance(snapshot, dict) else None
    if isinstance(sim, dict) and "sim_hour" in sim:
        return int(sim["sim_hour"])
    return int(ward_raw.get("hour", 12))


def build_simulation_response(
    parsed: dict,
    *,
    timestamp: str,
    ward_names: dict[str, str],
    features_by_ward: dict[str, dict],
    snapshot: dict,
    stress_before: int,
    agent_mode: str,
    model_label: str = "",
    grid_driver_default: str = "orchestrator",
    ward_driver_default: str = "ward agent",
    bid_reason: str = "orchestrator_ward_agent",
    reporter_title_default: str = "GridFlex alert",
    operator_note_default: str = "Generated by GridFlex orchestrator.",
) -> SimulationRunResponse:
    event_id = str(uuid.uuid4())
    ts = datetime.now(timezone.utc)
    grid_raw = parsed.get("grid_prediction", {})

    system_prediction = SystemPredictionDetail(
        event_type=EventType(grid_raw.get("event_type", "normal")),
        grid_stress_probability=float(grid_raw.get("grid_stress_probability", 0.2)),
        risk_level=RiskLevel(grid_raw.get("risk_level", "normal")),
        target_reduction_mw=int(grid_raw.get("target_reduction_mw", 0)),
        predicted_start_time=timestamp,
        predicted_end_time=(
            ts + timedelta(minutes=int(grid_raw.get("predicted_duration_minutes", 60)))
        ).isoformat(),
        predicted_duration_minutes=int(grid_raw.get("predicted_duration_minutes", 60)),
        drivers=list(grid_raw.get("drivers", [grid_driver_default])),
    )

    ward_predictions: list[WardPrediction] = []
    ward_decisions: list[WardAgentDecision] = []
    submitted_bids: list[Bid] = []

    for ward_raw in parsed.get("ward_predictions", []):
        ward_id = str(ward_raw.get("ward_id", ""))
        feat = features_by_ward.get(ward_id, {})
        ward_name = str(ward_raw.get("ward_name") or ward_names.get(ward_id, ward_id))
        duration = int(ward_raw.get("predicted_duration_minutes", 60))
        action_str = ward_raw.get("recommended_action", "none")
        load = float(feat.get("ward_load_proxy_mw", 0))
        flex = float(feat.get("ward_flexible_capacity_mw", 50))
        mult = float(feat.get("spike_multiplier", 1.0))
        delta = max(0.0, load * (mult - 1.0))
        try:
            action = RecommendedAction(action_str)
        except ValueError:
            action = RecommendedAction.none

        ward_predictions.append(
            WardPrediction(
                ward_id=ward_id,
                ward_name=ward_name,
                event_type=EventType(ward_raw.get("event_type", "normal")),
                event_probability=float(ward_raw.get("event_probability", 0.1)),
                risk_level=RiskLevel(ward_raw.get("risk_level", "normal")),
                predicted_start_time=timestamp,
                predicted_end_time=(ts + timedelta(minutes=duration)).isoformat(),
                predicted_duration_minutes=duration,
                predicted_peak_hour=int(
                    feat.get("hour", system_features_hour(snapshot, ward_raw))
                ),
                baseline_load_mw=float(ward_raw.get("baseline_load_mw", load)),
                forecast_load_mw=float(ward_raw.get("forecast_load_mw", load + delta)),
                expected_load_delta_mw=float(ward_raw.get("expected_load_delta_mw", delta)),
                ward_flexible_capacity_mw=float(ward_raw.get("ward_flexible_capacity_mw", flex)),
                recommended_action=action,
                recommended_bid_mw=float(ward_raw.get("recommended_bid_mw", 0)),
                max_bid_mw=float(ward_raw.get("max_bid_mw", flex)),
                confidence=float(ward_raw.get("confidence", 0.7)),
                drivers=list(ward_raw.get("drivers", [ward_driver_default])),
            )
        )

        bid = None
        decision = "no_bid"
        if ward_raw.get("submit_bid") and float(ward_raw.get("bid_quantity_mw", 0)) > 0:
            qty = float(ward_raw.get("bid_quantity_mw", 0))
            bid = Bid(
                bid_id=f"bid_{ward_id}_{uuid.uuid4().hex[:8]}",
                agent_id=f"agent_{ward_id}",
                ward_id=ward_id,
                bid_type=BidType.demand_reduction,
                quantity_mw=qty,
                max_quantity_mw=qty,
                price_per_mwh=float(ward_raw.get("bid_price_per_mwh", 75)),
                available_start_time=timestamp,
                available_end_time=(ts + timedelta(minutes=duration)).isoformat(),
                duration_minutes=duration,
                activation_minutes=10,
                confidence=float(ward_raw.get("confidence", 0.7)),
                comfort_impact="medium",
                status=DispatchStatus.submitted,
                reason=bid_reason,
            )
            decision = "submit_bid"
            submitted_bids.append(bid)

        ward_decisions.append(
            WardAgentDecision(
                agent_id=f"agent_{ward_id}",
                ward_id=ward_id,
                decision=decision,
                bid=bid,
            )
        )

    market_context = MarketContext(
        event_id=event_id,
        system_risk_level=system_prediction.risk_level,
        target_reduction_mw=system_prediction.target_reduction_mw,
        stress_score_before=stress_before,
    )
    market_result = market_clearing_agent.clear(
        submitted_bids,
        market_context,
        event_id=event_id,
        timestamp=timestamp,
    )

    rep_raw = parsed.get("reporter", {})
    reporter = ReporterOutput(
        alert=OperatorAlert(
            title=str(rep_raw.get("title", reporter_title_default)),
            severity=str(rep_raw.get("severity", system_prediction.risk_level.value)),
            summary=str(rep_raw.get("summary", "")),
            market_action=str(rep_raw.get("market_action", "")),
            impact=str(rep_raw.get("impact", "")),
            operator_note=str(rep_raw.get("operator_note", operator_note_default)),
        )
    )

    kepler_nodes = build_kepler_nodes(
        timestamp, ward_predictions, market_result, stress_score=stress_before
    )
    kepler_flows = build_kepler_flows(
        timestamp, market_result.accepted_bids, ward_predictions
    )

    meta = {**snapshot, "agent_mode": agent_mode}
    if model_label:
        meta["model_label"] = model_label

    return SimulationRunResponse(
        simulation_id=event_id,
        timestamp=timestamp,
        grid_prediction=system_prediction,
        ward_predictions=ward_predictions,
        ward_agent_decisions=ward_decisions,
        submitted_bids=submitted_bids,
        market_result=market_result,
        reporter=reporter,
        kepler_nodes=kepler_nodes,
        kepler_flows=kepler_flows,
        snapshot=meta,
    )
